app = 'latitude-llm-dashboard'

primary_region = 'mad'

[build]
  args = { NODE_ENV = "production" }
  dockerfile = './docker/Dockerfile'
  dockerignore = '../../.dockerignore'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  memory = '1gb'
  cpus = 1

[deploy]
  release_command = "pnpm --prefix packages/core db:migrate"
