# ./.tmuxinator.yml

name: latitude-llm
windows:
  - web: cd apps/web
  - apps: pnpm dev --filter='./apps/*' --filter='./packages/**'
  - docker: docker compose up
  - studio: cd packages/core && pnpm db:studio
