services:
  web:
    build:
      context: .
      dockerfile: apps/web/docker/Dockerfile
    ports:
      - '3000:3000'
      - '4983:4983'
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
    depends_on:
      - db
    env_file:
      - apps/web/.env
    command: pnpm run dev

  api:
    build:
      context: .
      dockerfile: apps/api/docker/Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./apps/api/package.json:/app/apps/api/package.json
    depends_on:
      - db
    command: pnpm run dev

  elastic:
    image: elasticsearch:8.14.1
    environment:
      - 'discovery.type=single-node'
      - 'ELASTIC_USERNAME=latitude'
      - 'ELASTIC_PASSWORD=secret'

  core:
    build:
      context: .
      dockerfile: packages/core/docker/Dockerfile
    volumes:
      - ./packages/core/src:/app/packages/core/src
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=latitude'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./docker/pgdata:/var/lib/postgresql/data
