services:
  db:
    image: postgres:15.8
    environment:
      - 'POSTGRES_USER=latitude'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./docker/pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025

  web:
    build:
      context: .
      dockerfile: apps/web/docker/Dockerfile
      args:
        - BUILDING_CONTAINER=true
        - NODE_ENV=production
        - SENTRY_ORG=$SENTRY_ORG
        - SENTRY_PROJECT=$SENTRY_PROJECT
        - SENTRY_DSN=$SENTRY_DSN
        - NEXT_PUBLIC_POSTHOG_KEY=$NEXT_PUBLIC_POSTHOG_KEY
        - NEXT_PUBLIC_POSTHOG_HOST=$NEXT_PUBLIC_POSTHOG_HOST
    profiles: [building]
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - FROM_MAILER_EMAIL=hello@latitude.so
      - DATABASE_URL=postgresql://latitude:secret@db:5432/latitude
      - QUEUE_PORT=6379
      - QUEUE_HOST=0.0.0.0
      - CACHE_PORT=6379
      - CACHE_HOST=0.0.0.0
      - GATEWAY_PORT=8787
      - GATEWAY_HOSTNAME=localhost
      - GATEWAY_SSL=false
      - LATITUDE_DOMAIN=latitude.so
      - LATITUDE_URL=http://localhost:3000
      - WEBSOCKETS_SERVER=http://localhost:4002
      - WEBSOCKET_SECRET_TOKEN_KEY=secret-token-key
      - WEBSOCKET_REFRESH_SECRET_TOKEN_KEY=refresh-refresh-token-key
      - WORKERS_WEBSOCKET_SECRET_TOKEN=workers-secret-token
      - DRIVE_DISK=local
      - FILE_PUBLIC_PATH=''
      - FILES_STORAGE_PATH=''
      - DEFAULT_PROJECT_ID=1
      - DEFAULT_PROVIDER_API_KEY=d32da7c2-94fd-49c3-8dca-b57a5c3bbe27
      - NEXT_PUBLIC_POSTHOG_KEY=''
      - NEXT_PUBLIC_POSTHOG_HOST=''
      - DATASET_GENERATOR_DOCUMENT_PATH=generator
      - TEMPLATES_SUGGESTION_PROMPT_PATH=evaluation-suggestions
    depends_on:
      - db
      - redis

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/docker/Dockerfile
    profiles: [building]
    environment:
      - CACHE_HOST=redis
      - DATABASE_URL=postgresql://latitude:secret@db:5432/latitude
      - DEFAULT_PROJECT_ID=1
      - DEFAULT_PROVIDER_API_KEY=test
      - FROM_MAILER_EMAIL=jon@winterfell.com
      - LATITUDE_DOMAIN=web
      - LATITUDE_URL=http://web:8080
      - NODE_ENV=production
      - QUEUE_HOST=redis
      - WEBSOCKETS_SERVER=websockets
      - WEBSOCKET_REFRESH_SECRET_TOKEN_KEY=test
      - WEBSOCKET_SECRET_TOKEN_KEY=test
      - WORKERS_WEBSOCKET_SECRET_TOKEN=test
      - HOSTNAME=localhost
    depends_on:
      - db
      - redis

  workers:
    build:
      context: .
      dockerfile: apps/workers/docker/Dockerfile
    profiles: [building]
    environment:
      - CACHE_HOST=redis
      - DATABASE_URL=postgresql://latitude:secret@db:5432/latitude
      - DEFAULT_PROJECT_ID=1
      - DEFAULT_PROVIDER_API_KEY=test
      - FROM_MAILER_EMAIL=jon@winterfell.com
      - LATITUDE_DOMAIN=web
      - LATITUDE_URL=http://web:8080
      - NODE_ENV=production
      - QUEUE_HOST=redis
      - WEBSOCKETS_SERVER=websockets
      - WEBSOCKET_REFRESH_SECRET_TOKEN_KEY=test
      - WEBSOCKET_SECRET_TOKEN_KEY=test
      - WORKERS_WEBSOCKET_SECRET_TOKEN=test
    depends_on:
      - db
      - redis

  core:
    build:
      context: .
      dockerfile: packages/core/docker/Dockerfile
    profiles: [building]
    environment:
      - NODE_ENV=production
    depends_on:
      - db
