services:
  web:
    build:
      context: .
      dockerfile: apps/web/docker/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./packages/env:/app/packages/env
      - ./packages/core:/app/packages/core
      - ./apps/web:/app/apps/web
    depends_on:
      - db
    command: pnpm run dev

  api:
    build:
      context: .
      dockerfile: apps/api/docker/Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./packages/env:/app/packages/env
      - ./packages/core:/app/packages/core
      - ./apps/api:/app/apps/api
    depends_on:
      - db
    command: pnpm run dev

  elastic:
    image: elasticsearch:8.14.1
    environment:
      - 'discovery.type=single-node'
      - 'ELASTIC_USERNAME=latitude'
      - 'ELASTIC_PASSWORD=secret'

  core:
    build:
      context: .
      dockerfile: packages/core/docker/Dockerfile
    ports:
      # Used to run Drizzle studio in development
      - '3002:3002'
    environment:
      # Used in entrypoint.sh to set NODE_ENV
      - 'NODE_ENV=development'
    volumes:
      - ./packages/core:/app/packages/core
      - ./packages/env:/app/packages/env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=latitude'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./docker/pgdata:/var/lib/postgresql/data
