services:
  base:
    image: latitudedata/base
    build:
      context: .
      dockerfile: docker/Dockerfile.base
    restart: 'none'

  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=latitude'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./docker/pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'

  web:
    build:
      context: .
      dockerfile: apps/web/docker/Dockerfile
    profiles: [building]
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/docker/Dockerfile
    profiles: [building]
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis

  workers:
    build:
      context: .
      dockerfile: apps/workers/docker/Dockerfile
    profiles: [building]
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis
