name: CI and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'packages/**'
      - '.github/workflows/**'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      workflow_call: true

  test:
    uses: ./.github/workflows/test.yml
    with:
      workflow_call: true

  deploy:
    needs: [lint, test]
    strategy:
      matrix:
        app: [gateway, websockets, workers]
    uses: ./.github/workflows/deploy-app.yml
    with:
      app-name: ${{ matrix.app }}
    secrets: inherit
