name: Deploy App

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.check_changes.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for relevant changes
        id: check_changes
        run: |
          changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changes detected:"
          echo "$changes"
          if echo "$changes" | grep -qE "^(apps/infra/|apps/${{ inputs.app-name }}/|packages/)"
          then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: check_changes
    if: needs.check_changes.outputs.changes_detected == 'true'
    uses: ./.github/workflows/deploy-common.yml
    with:
      working-directory: apps/infra
      stack-name: ${{ inputs.app-name }}-production
    secrets: inherit

concurrency:
  group: production-${{ inputs.app-name }}
  cancel-in-progress: false
