name: Deploy Websockets

on:
  push:
    branches:
      - main
    paths:
      - 'apps/websockets/**'
      - 'apps/infra/src/deployments/websockets.ts'
      - 'apps/infra/src/deployments/shared.ts'
      - 'packages/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-common.yml
    with:
      working-directory: apps/infra
      stack-name: websockets-production
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ARN_OF_IAM_ROLE_TO_ASSUME: ${{ secrets.ARN_OF_IAM_ROLE_TO_ASSUME }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
