name: Deploy Gateway

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      ARN_OF_IAM_ROLE_TO_ASSUME:
        required: true
      PULUMI_CONFIG_PASSPHRASE:
        required: true
      SENTRY_AUTH_TOKEN:
        required: true

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.check_changes.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check for relevant changes
        id: check_changes
        run: |
          changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changes detected:"
          echo "$changes"
          if echo "$changes" | grep -qE "^(apps/infra/|apps/gateway/|packages/)"
          then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi
  deployment:
    needs: check_changes
    if: needs.check_changes.outputs.changes_detected == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        working-directory: apps/infra

      - name: Setup Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.ARN_OF_IAM_ROLE_TO_ASSUME }}
          role-session-name: WebDeployment
          aws-region: eu-central-1
          role-skip-session-tagging: true

      - name: Generate unique image tag
        run: echo "IMAGE_TAG=$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build & push docker images
        working-directory: apps/infra
        run: |
          echo "Deploying Pulumi stack: docker-production-gateway"
          pulumi up --stack docker-production-gateway --yes
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Create new task definition
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition LatitudeLLMGatewayTaskFamily --query 'taskDefinition')
          NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) | .containerDefinitions[0].image = "'"$AWS_ACCOUNT_ID"'.dkr.ecr.eu-central-1.amazonaws.com/latitude-llm-gateway-repo-b859826:${{ env.IMAGE_TAG }}"')
          echo $NEW_TASK_DEFINITION > new-task-definition.json
          NEW_TASK_DEFINITION_ARN=$(aws ecs register-task-definition --cli-input-json file://new-task-definition.json --query taskDefinition.taskDefinitionArn --output text)
          echo "NEW_TASK_DEFINITION_ARN=$NEW_TASK_DEFINITION_ARN" >> $GITHUB_ENV
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      - name: Update AppSpec with new task definition
        run: |
          sed -i 's|TaskDefinition: .*|TaskDefinition: '"$NEW_TASK_DEFINITION_ARN"'|' apps/gateway/appspec.yml

      - name: Deploy with CodeDeploy
        working-directory: apps/gateway
        run: |
          echo "Deploying branch ${{ github.ref }} to production"
          commit_hash=`git rev-parse HEAD`
          appspec_content=$(cat appspec.yml | jq -Rs .)
          aws deploy create-deployment \
            --application-name LatitudeLLMCodeDeployGateway \
            --deployment-group-name LatitudeLLMGatewayDeploymentGroup \
            --revision "{\"revisionType\": \"AppSpecContent\", \"appSpecContent\": {\"content\": $appspec_content}}"

concurrency:
  group: production-gateway
  cancel-in-progress: false
